version: '3.5'
services:
  keyrock:
    image: fiware/idm:7.6.0
    container_name: keyrock
    hostname: keyrock
    depends_on: 
      - mysql-db
    ports: 
      - 3005:3005
      - 443:443
    expose:
      - 3005
      - 443
    networks:
      default:
        ipv4_address: 172.18.1.5
    environment: 
      - IDM_DB_HOST=mysql-db
      # idm
      - IDM_DB_PASS=secret
      - IDM_DB_USER=root
      - IDM_HOST=http://localhost:3005
      - IDM_PORT=3005
      - IDM_HTTPS_ENABLED=false
      - IDM_HTTPS_PORT=443
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@test.com
      - IDM_ADMIN_PASS=1234

  fiware-pep-proxy:
    image: fiware/pep-proxy
    container_name: fiware-pep-proxy
    hostname: fiware-pep-proxy
    networks: 
      default:
        ipv4_address: 172.18.1.15
    depends_on: 
      - keyrock
    ports: 
      - 3051:3051
    expose: 
      - 3051
    environment: 
      - PEP_PROXY_APP_HOST=data-storage
      - PEP_PROXY_APP_PORT=80
      - PEP_PROXY_PORT=3051
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_APP_ID=c24f30ba-8eca-4933-a840-60812e046d32
      - PEP_PROXY_USERNAME=pep_proxy_59fdc158-5b66-480b-90ab-6f56216d4739
      - PEP_PASSWORD=pep_proxy_b42a8b38-52c5-43af-ad3d-c2001714ba91
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=1234
  orion-proxy:
    image: fiware/pep-proxy
    container_name: orion-proxy
    hostname: orion-proxy
    networks: 
      - default
    depends_on: 
      - keyrock
    ports: 
      - 1027:1027
    expose: 
      - 1027
    environment: 
      - PEP_PROXY_APP_HOST=fiware-orion
      - PEP_PROXY_APP_PORT=1026
      - PEP_PROXY_PORT=1027
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3005
      - PEP_PROXY_APP_ID=c24f30ba-8eca-4933-a840-60812e046d32
      - PEP_PROXY_USERNAME=pep_proxy_59fdc158-5b66-480b-90ab-6f56216d4739
      - PEP_PASSWORD=pep_proxy_b42a8b38-52c5-43af-ad3d-c2001714ba91
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=1234

  fiware-orion:
    image: fiware/orion
    hostname: fiware-orion
    container_name: fiware-orion
    depends_on:
      - mongo-orion
    networks:
      - default
    expose: 
      - 1026
    ports:
      - 1026:1026
    command: -dbhost mongo-orion -logLevel DEBUG -noCache


  mysql-db:
      restart: always
      image: mysql:5.7
      hostname: mysql-db
      container_name: mysql-db
      expose:
          - 3306
      ports:
          - 3306:3306
      networks:
          default:
              ipv4_address: 172.18.1.6
      environment:
          # Development use only
          # Use Docker Secrets for Sensitive Data
          - 'MYSQL_ROOT_PASSWORD=secret'
          - 'MYSQL_ROOT_HOST=172.18.1.5'
      volumes:
          - mysql-db:/var/lib/mysql
  mongo:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
      MONGO_INITDB_DATABASE: products_db
    networks: 
      - default
    ports: 
     - 27018:27017

  mongo-orion:
    image: mongo:latest
    container_name: mongo-orion
    hostname: mongo-orion
    restart: always
    expose:
      - 27017
    ports: 
      - 27017:27017
    networks:
      - default
    volumes:
      - ./mongo-orion:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: mongopwd

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_SERVER: mongo
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - default

  websvr:
    image:  php:8.2-apache
    # build: ./work
    container_name: websvr
    volumes:
      - ./work/src:/var/www/html
    ports:
      - 80:80
    expose: 
      - 3051
    links:
      - mongo
      - keyrock
    depends_on:
      - mongo
      - keyrock
    networks:
      - default

  data-storage:
    build: 
      context: ./work/restapi
      dockerfile: Dockerfile
    hostname: data-storage
    container_name: data-storage
    volumes: 
      - ./work/restapi:/var/www/html
    networks: 
      - default
    ports:
      - 3050:80
  # phpmyadmin:
  #   image: phpmyadmin
  #   ports:
  #     - 8002:80
  #   environment:
  #     - PMA_HOST=mysql-db
  #     - PMA_PORT=3306
  #   depends_on:
  #     - mysql-db
  #   networks:
  #     default:
  #       ipv4_address: 172.18.1.9
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes:
    mysql-db: ~